name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/unica-isde/unica-isde.github.io/dispatches --data "{\"event_type\": \"deploy\", \"client_payload\": {}}"

